
CLEANFILES= *.ii

.pa.o:
	if LD_LIBRARY_PATH=$(top_srcdir)/parser \
	$(OCC) -u.pa -c -SPlasma -SWrapper -SMutex -STMutex \
	-d-include$(top_srcdir)/src/plasma-interface.h -I../../src $(INCLUDES) \
	-d"-MT $@" -d-MD -d-MP -d"-MF$(DEPDIR)/$*.Tpo" -- $(CXXFLAGS) -o $@ $< ; \
	then mv "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po" ; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
