
CLEANFILES= *.ii

PLASMA = $(top_srcdir)/scripts/plasma --devel=$(top_srcdir)

AM_LDFLAGS = -L$(top_srcdir)/src/.libs -Wl,-R$(top_srcdir)/src/.libs \
	-L$(top_srcdir)/qt/.libs -Wl,-R$(top_srcdir)/qt/.libs \
	-L$(top_srcdir)/gc/.libs -Wl,-R$(top_srcdir)/gc/.libs
# This must be added to each C++ file's LDADD variable.
CXX_LDADD =  -lplasma -lqt -lgc -ldl

CXXLD = $(CXX)
LINK = $(PLASMA) -o $@
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@

DEPENDENCIES = $(top_srcdir)/src/.libs/libplasma.a

# Use this for libtool linking- I didn't want the wrapper scripts, so I just do it manually.
#LDADD = $(top_srcdir)/src/libplasma.la $(top_srcdir)/qt/libqt.la $(top_srcdir)/gc/libgc.la -ldl
#LINK = $(LIBTOOL) --mode=link $(CXX) -o $@

.pa.o:
	if $(PLASMA) $(INCLUDES) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo $(CXXFLAGS) -c -o $@ $< ; \
	then mv "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po" ; \
	else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; \
	fi
