#!/usr/bin/env perl
# -- -*-perl-*-a
#
# Tests used in this regression.

use FindBin;
use lib "$FindBin::RealBin/..";
use rdriver;
use strict;
use Data::Dumper;

my @Tests = (
	     # Basic eav run.
	     {
	      cmd     => "./eav 4 50 10 128 40 4 500 50",
	      checker => \&check_eav,
	     },
	    );

doTest(\@Tests);

##
## <TESTS>
##

# The searches are done independently so that order is not
# important- we just wantto make sure that the strings are present.
sub check_eav {
  
  str_rdiff(@_[0],[
		   "Comms starting.",
		   ]);

  str_rdiff(@_[0],[
		   "TP agent starting.",
		   ]);

  str_rdiff(@_[0],[
		   "Disk manager starting.",
		   ]);

  str_rdiff(@_[0],[
		   "The users have all finished.",
		   ]);

  # We allow some variable for the number of transactions.
  my $exp_nt = 1899;
  my $var = 30;
  my @lines = split /\n/,@_[0];
  for (@lines) {
    if (/Total of (\d+) in/) {
      my $nt = eval $1;
      if (($nt > ($exp_nt+$var)) || ($nt < ($exp_nt-$var))) {
	print "Incorrect # of transactions- expected $exp_nt with variable of $var, found $nt.\n";
	die;
      }
    }
  }
}

##
## </TESTS>
##
