//
// The main parser class.  This wraps the parser internals,
// which are generated by Lemon.
//

#ifndef _CPARSER_H_
#define _CPARSER_H_

struct Tokens;

// Wrapper class.  The copy-constructor is shallow
// and there is no destructor b/c allocation is garbage collected.
class CParser : public gc {
public:
  CParser();
  CParser(const CParser &cp) : _parser(cp._parser) {}

  void parse(int t,Tokens tk);
private:
  void *_parser;  // The parser (opaque type generated by Lemon).
};

#endif
