#!/usr/bin/env perl 
# -- -*-perl-*-a
#
# Tests used in this regression.

use lib "..";
use rdriver;
use strict;
use Data::Dumper;

my @Tests = (
			 # Basic check of multiple .c files.
			 {
			  cmd     => "./minicc -ast tests/in1.c tests/in2.c",
			  diff    => "tests/test1.out",
			 },
			 # Checks that a parsing error will be reported.
			 {
			  cmd     => "./minicc -ast tests/in3.c",
			  diff    => "tests/test2.out",
			  stderr  => 1,
			  fail    => 1,
			 },
			 # Large test of all supported features.
			 {
			  cmd     => "./minicc -ast tests/in4.c",
			  diff    => "tests/test3.out",
			 },
			 # Simple symbol-table parsing.
			 {
			  cmd     => "./minicc -syms tests/in5.c",
			  diff    => "tests/test4.out",
			 },
			 # Simple symbol-table parsing.
			 {
			  cmd     => "./minicc -syms tests/in6.c",
			  diff    => "tests/test5.out",
			  stderr  => 1,
			  fail    => 1,
			 },
			 # Simple symbol-table parsing.
			 {
			  cmd     => "./minicc -syms tests/in7.c",
			  diff    => "tests/test6.out",
			  stderr  => 1,
			  fail    => 1,
			 },
	    );

doTest(\@Tests);

##
## <TESTS>
##

##
## </TESTS>
##
