//
// Copyright (C) 2005 by Freescale Semiconductor Inc.  All rights reserved.
//
// You may distribute under the terms of the Artistic License, as specified in
// the COPYING file.
//
//
// This defines the Tokens structure, which is used to pass data from
// the tokenizer to the parser.
//

#ifndef _TOKENS_H_
#define _TOKENS_H_

struct Tokens {
  int _tok;        // The token itself- these are defined by lemon.
  int _ln;         // Line number.
  const char *_fn; // File name.
  union {
    // For strings or identifiers:  Pointer to the
    // data and its length.
    struct {
      const char *p;
      int l;
    } _str;
    // For integer data.
    int _int;
    // For floating point data.
    double _fp;
  };
};

// This is explicitly defined b/c it's not generated by the tokenizer-
// it's used to signal that all files have been parsed.
#define ALL_DONE -1

#endif
