#! /bin/sh -x

rm -f Makefile.md README.md qtmd.h qtmdb.S qtmdc.c qtmds.S configuration

case $1 in
	axp*)
		: "DEC AXP"
		case $1 in
			axp-osf1*)
				: "Compile using /bin/cc under OSF 1.x."
				ln -s md/axp.1.Makefile Makefile.md
				;;
			axp-osf2*)
				: "Compile using /bin/cc under OSF 2.x."
				ln -s md/axp.1.Makefile Makefile.md
				;;
			*)
				: "Compile using GNU CC."
				ln -s md/axp.Makefile Makefile.md
				;;
		esac

		ln -s md/axp.h qtmd.h
		ln -s md/axp.c qtmdc.c
		ln -s md/axp.S qtmds.S
		ln -s md/axp_b.S qtmdb.S
		ln -s md/axp.README README.md
		iter_init=1000000000
		iter_runone=10000000
		iter_blockint=10000000
		iter_blockfloat=10000000
		iter_vainit0=10000000
		iter_vainit2=10000000
		iter_vainit4=10000000
		iter_vainit8=10000000
		iter_vastart0=10000000
		iter_vastart2=10000000
		iter_vastart4=10000000
		iter_vastart8=10000000
		iter_bench_call_reg=10000000
		iter_bench_call_imm=10000000
		iter_bench_add=100000000
		iter_bench_load=100000000
		;;

       hppa*)
		: "HP's PA-RISC 1.1 processors."

		case $1 in
			hppa-cnx-spp*)
				: "Convex SPP (PA-RISC 1.1 processors)."
				ln -s md/hppa-cnx.Makefile Makefile.md
				;;
			*)
				ln -s md/hppa.Makefile Makefile.md
				;;
		esac

		ln -s md/hppa.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/hppa.S qtmds.S
		ln -s md/hppa_b.S qtmdb.S
		iter_init=10000000
		iter_runone=1000000
		iter_blockint=1000000
		iter_blockfloat=1000000
		iter_vainit0=1000000
		iter_vainit2=1000000
		iter_vainit4=1000000
		iter_vainit8=1000000
		iter_vastart0=1000000
		iter_vastart2=1000000
		iter_vastart4=1000000
		iter_vastart8=1000000
		iter_bench_call_reg=10000000
		iter_bench_call_imm=10000000
		iter_bench_add=100000000
		iter_bench_load=100000000
		;;

	iX86*)
		case $1 in
			iX86-ss*)
				: "Assemlber comments '//'"
				sed 's/\/\*/\/\//' < md/i386.S > qtmds.S
				sed 's/\/\*/\/\//' < md/i386_b.S > qtmdb.S
				;;
				
			*)
				ln -s md/i386.S qtmds.S
				ln -s md/i386_b.S qtmdb.S
				;;
		esac
		: "Intel 80386 and compatibles (not '286...)"
		ln -s md/default.Makefile Makefile.md
		ln -s md/i386.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/i386.README README.md
		iter_init=10000000
		iter_runone=1000000
		iter_blockint=1000000
		iter_blockfloat=1000000
		iter_vainit0=1000000
		iter_vainit2=1000000
		iter_vainit4=1000000
		iter_vainit8=1000000
		iter_vastart0=1000000
		iter_vastart2=1000000
		iter_vastart4=1000000
		iter_vastart8=1000000
		iter_bench_call_reg=1000000
		iter_bench_call_imm=1000000
		iter_bench_add=100000000
		iter_bench_load=10000000
		;;

	m68k)
		: "Motorola 68000 family -- incomplete!"
		ln -s md/default.Makefile Makefile.md
		ln -s md/m68k.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/m68k.S qtmds.S
		ln -s md/m68k_b.S qtmdb.S
		ln -s md/null.README README.md
		;;

	m88k)
		: "Motorola 88000 family"
		ln -s md/m88k.Makefile Makefile.md
		ln -s md/m88k.h qtmd.h
		ln -s md/m88k.c qtmdc.c
		ln -s md/m88k.S qtmds.S
		ln -s md/m88k_b.S qtmdb.S
		ln -s md/null.README README.md
		iter_init=1000000
		iter_runone=100000
		iter_blockint=100000
		iter_blockfloat=100000
		iter_vainit0=100000
		iter_vainit2=100000
		iter_vainit4=100000
		iter_vainit8=100000
		iter_vastart0=100000
		iter_vastart2=100000
		iter_vastart4=100000
		iter_vastart8=100000
		iter_bench_call_reg=100000000
		iter_bench_call_imm=100000000
		iter_bench_add=1000000000
		iter_bench_load=100000000
		;;

	ppc)
		: "PowerPC"
		ln -s md/ppc.Makefile Makefile.md
		ln -s md/ppc.h qtmd.h
		ln -s md/ppc.S qtmds.S
		ln -s md/ppc_b.S qtmdb.S
		ln -s md/null.c qtmdc.c
		ln -s md/null.README README.md
		iter_init=1000000
		iter_runone=100000
		iter_blockint=100000
		iter_blockfloat=100000
		iter_vainit0=100000
		iter_vainit2=100000
		iter_vainit4=100000
		iter_vainit8=100000
		iter_vastart0=100000
		iter_vastart2=100000
		iter_vastart4=100000
		iter_vastart8=100000
		iter_bench_call_reg=100000000
		iter_bench_call_imm=100000000
		iter_bench_add=1000000000
		iter_bench_load=100000000
		;;

	mips*)
		: "MIPS R2000 and R3000."

		case $1 in
			mips-irix5*)
				: "Silicon Graphics Irix with dynamic linking"
				: "Use mips for irix4."
				ln -s md/mips-irix5.S qtmds.S
				;;
			*)
				ln -s md/mips.S qtmds.S
				;;
		esac

		ln -s md/default.Makefile Makefile.md
		ln -s md/mips.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/mips_b.S qtmdb.S
		ln -s md/null.README README.md
		iter_init=10000000
		iter_runone=10000000
		iter_blockint=10000000
		iter_blockfloat=10000000
		iter_vainit0=1000000
		iter_vainit2=1000000
		iter_vainit4=1000000
		iter_vainit8=1000000
		iter_vastart0=1000000
		iter_vastart2=1000000
		iter_vastart4=1000000
		iter_vastart8=1000000
		iter_bench_call_reg=100000000
		iter_bench_call_imm=100000000
		iter_bench_add=1000000000
		iter_bench_load=100000000
		;;

	sparc*)
		: "SPARC processors"
		case $1 in
			sparc-os2*)
				sed 's/_qt_/qt_/' md/sparc.S > qtmds.S
				sed 's/_b_/b_/' md/sparc_b.S > qtmdb.S
				ln -s md/solaris.README README.md
				;;
			*)
				ln -s md/sparc.S qtmds.S
				ln -s md/sparc_b.S qtmdb.S
				ln -s md/null.README README.md
				;;
		esac

		ln -s md/default.Makefile Makefile.md
		ln -s md/sparc.h qtmd.h
		ln -s md/null.c qtmdc.c
		iter_init=10000000
		iter_runone=1000000
		iter_blockint=1000000
		iter_blockfloat=1000000
		iter_vainit0=1000000
		iter_vainit2=1000000
		iter_vainit4=1000000
		iter_vainit8=1000000
		iter_vastart0=1000000
		iter_vastart2=1000000
		iter_vastart4=1000000
		iter_vastart8=1000000
		iter_bench_call_reg=10000000
		iter_bench_call_imm=10000000
		iter_bench_add=100000000
		iter_bench_load=100000000
		;;

	vax*)
		: "DEC VAX processors."
		ln -s md/default.Makefile Makefile.md
		ln -s md/vax.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/vax.S qtmds.S
		ln -s md/vax_b.S qtmdb.S
		ln -s md/null.README README.md
		iter_init=1000000
		iter_runone=100000
		iter_blockint=100000
		iter_blockfloat=100000
		iter_vainit0=100000
		iter_vainit2=100000
		iter_vainit4=100000
		iter_vainit8=100000
		iter_vastart0=100000
		iter_vastart2=100000
		iter_vastart4=100000
		iter_vastart8=100000
		iter_bench_call_reg=10000000
		iter_bench_call_imm=10000000
		iter_bench_add=10000000
		iter_bench_load=1000000
		;;

	ksr1)
		: "Kendall Square Research model KSR-1."
		: "Varargs is not currently supported."
		ln -s md/ksr1.Makefile Makefile.md
		ln -s md/ksr1.h qtmd.h
		ln -s md/null.c qtmdc.c
		ln -s md/ksr1.S qtmds.S
		ln -s md/ksr1_b.S qtmdb.S
		ln -s md/null.README README.md
		iter_init=1000000
		iter_runone=100000
		iter_blockint=100000
		iter_blockfloat=100000
		iter_vainit0=100000
		iter_vainit2=100000
		iter_vainit4=100000
		iter_vainit8=100000
		iter_vastart0=100000
		iter_vastart2=100000
		iter_vastart4=100000
		iter_vastart8=100000
		iter_bench_call_reg=10000000
		iter_bench_call_imm=10000000
		iter_bench_add=10000000
		iter_bench_load=1000000
		;;

	clean)
		: Deconfigure
		exit 0
		;;

	*)
		echo "Unknown configuration:  $1"
		exit 1
		;;
esac

#cat Makefile.md Makefile.base > Makefile

echo set config_machine=$1 >> configuration
echo set config_init=$iter_init >> configuration
echo set config_runone=$iter_runone >> configuration
echo set config_blockint=$iter_blockint >> configuration
echo set config_blockfloat=$iter_blockfloat >> configuration
echo set config_vainit0=$iter_vainit0 >> configuration
echo set config_vainit2=$iter_vainit2 >> configuration
echo set config_vainit4=$iter_vainit4 >> configuration
echo set config_vainit8=$iter_vainit8 >> configuration
echo set config_vastart0=$iter_vastart0 >> configuration
echo set config_vastart2=$iter_vastart2 >> configuration
echo set config_vastart4=$iter_vastart4 >> configuration
echo set config_vastart8=$iter_vastart8 >> configuration
echo set config_bcall_reg=$iter_bench_call_reg >> configuration
echo set config_bcall_imm=$iter_bench_call_imm >> configuration
echo set config_b_add=$iter_bench_add >> configuration
echo set config_b_load=$iter_bench_load >> configuration
