#!/bin/sh
##
## This simple script is used to test that we can
## correctly build from CVS.  Generally you would
## copy this to a test project area, make it read-only,
## and then run it.
##
## I recommend making it read-only so that you remember
## to edit the version in CVS, not the copy that is
## run.
##
rm -rf plasma plasma-* bin lib share include

prefix=`pwd`

# Try to configure from CVS.
(   cvs checkout plasma && \
	cd plasma && \
	./configure )

# Build the project.
(   cvs checkout plasma && \
    cd plasma && \
    ./autogen.sh --enable-opt --prefix=${prefix} && \
    make check &&
    make install &&
    make dist )
 
# Place installation checks here.
if [ ! -f include/gc/gc_cpp.h ] ; then
    echo "!!!"
    echo "!!! Error:  GC C++ headers not installed."
    echo "!!! "
    exit 1
fi

# Now build from the distribution.
( tar zxvf plasma/plasma-*.tar.gz && \
    cd plasma-* && \
    ./configure --enable-opt --prefix=${prefix} && \
    make check ) && echo "Test build SUCCEEDED."
