#!/bin/sh
##
## This simple script is used to test that we can
## correctly build from CVS.  Generally you would
## copy this to a test project area and then run it.
##
rm -rf plasma bin lib share include && \
cvs checkout plasma && \
cd plasma && \
./autogen.sh --enable-opt --prefix=$proj && \
make check &&
make install

if [ ! -f include/gc_cpp.h ] ; then
    echo "Error:  GC C++ headers not installed."
    exit 1
fi


